apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: krakend-test-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/akashmate/krakend-test-env-app.git'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: krakend-test-prj
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
