apiVersion: v1
kind: Service
metadata:
  name: krakend-test-service
  namespace: krakend-test-prj
spec:
  selector:
    app: krakend-d
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 31719
  type: NodePort
